POST http://localhost:8002/api/auth/login
Content-Type: application/json

{
  "userId": "test",
  "userPassword": "1234"
}

###
DELETE http://localhost:8082/api/auth/logout
X-USER_ID:userId
Content-Type: application/json

{
  "refreshToken" : "refreshToken"
}
